version: '2'
services:
  nginx:
      image: nginx
      restart: always
      ports:
          - "80:8090"
      volumes:
         - /etc/localtime:/etc/localtime:ro
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      depends_on:
        - znserver
  simulatorsrv:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /simulatorsrv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./simulator_restfulapi:/simulatorsrv
      - ./dist/log:/dist/log
    environment:
      - listenport=8080
    ports:
       - "8080:8080"
    expose:
       - "8080"
  znserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./srv:/app
      - ./dist/log:/dist/log
    environment:
      - MONGO_URL=mongodb://172.17.0.1:27018/zhongnandb
      - platformserverurl=http://172.17.0.1:8080
      - listenport=3005
    links:
      - mongodb
    ports:
       - "3005:3005"
    expose:
       - "3005"
  mongodb:
    image:  mongo:3.4
    restart: always
    expose:
       - "27018"
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - "/var/db100/dbdata:/data/db -d"
    ports:
       - "27018:27017"
