version: '2'
services:
  nginx:
      image: nginx
      restart: always
      ports:
          - "80:8080"
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      depends_on:
        - znserver
  simulatorsrv:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /simulatorsrv
    volumes:
      - ./simulator_restfulapi:/simulatorsrv
      - ./dist:/
    environment:
      - listenport=8090
    ports:
       - "8090:8090"
    expose:
       - "8090"
  znserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./srv:/app
      - ./dist:/
    environment:
      - MONGO_URL=mongodb://172.17.0.1:27018/zhongnandb
      - platformserverurl=http://172.17.0.1:8090
      - listenport=3005
    links:
      - mongodb
    ports:
       - "3005:3005"
    expose:
       - "3005"
  mongodb:
    image:  mongo:3.4
    restart: always
    expose:
       - "27018"
    volumes:
       - "/var/db100/dbdata:/data/db -d"
    ports:
       - "27018:27017"
