  nginx:
      image: nginx
      restart: always
      expose:
         - "80"
      ports:
          - "80:8090"
      external_links:
        - znserver
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - /app/zn/deploy/dist:/usr/share/nginx/html
